# Generated by Django 6.0.1 on 2026-02-10 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backends', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='menulist',
            table='menulist',
        ),
    ]
