# Generated by Django 6.0.1 on 2026-02-12 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backends', '0003_product_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='level_name',
        ),
        migrations.AddField(
            model_name='membership',
            name='membership_choice',
            field=models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], default='Bronze', max_length=50),
            preserve_default=False,
        ),
    ]
