# Generated by Django 6.0.1 on 2026-02-12 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backends', '0004_remove_membership_level_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='membership_choice',
            new_name='tier',
        ),
        migrations.AddField(
            model_name='membership',
            name='benefits',
            field=models.TextField(blank=True, help_text='Enter each benefit on a new line'),
        ),
        migrations.AddField(
            model_name='membership',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membership',
            name='name',
            field=models.CharField(default='Standard Membership', max_length=100),
        ),
        migrations.AddField(
            model_name='membership',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='membership',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
