# Generated by Django 6.0.1 on 2026-02-13 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backends', '0006_customer_points_customer_points_discount_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='price',
        ),
    ]
