# Generated by Django 6.0.1 on 2026-02-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backends', '0007_remove_membership_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attribute',
            options={'verbose_name': 'Attribute', 'verbose_name_plural': 'Attributes'},
        ),
        migrations.AlterModelOptions(
            name='attributevalue',
            options={'verbose_name': 'Attribute Value', 'verbose_name_plural': 'Attribute Values'},
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Brand', 'verbose_name_plural': 'Brands'},
        ),
        migrations.AlterModelOptions(
            name='cancelledorder',
            options={'verbose_name': 'Cancelled Order', 'verbose_name_plural': 'Cancelled Orders'},
        ),
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Cart', 'verbose_name_plural': 'Carts'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'Cart Item', 'verbose_name_plural': 'Cart Items'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterModelOptions(
            name='customersupport',
            options={'verbose_name': 'Customer Support', 'verbose_name_plural': 'Customer Support'},
        ),
        migrations.AlterModelOptions(
            name='customersupportfeedback',
            options={'verbose_name': 'Customer Support Feedback', 'verbose_name_plural': 'Customer Support Feedback'},
        ),
        migrations.AlterModelOptions(
            name='customersupportticket',
            options={'verbose_name': 'Customer Support Ticket', 'verbose_name_plural': 'Customer Support Tickets'},
        ),
        migrations.AlterModelOptions(
            name='discountcoupon',
            options={'verbose_name': 'Discount Coupon', 'verbose_name_plural': 'Discount Coupons'},
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name': 'Inventory', 'verbose_name_plural': 'Inventory'},
        ),
        migrations.AlterModelOptions(
            name='membership',
            options={'verbose_name': 'Membership', 'verbose_name_plural': 'Memberships'},
        ),
        migrations.AlterModelOptions(
            name='menulist',
            options={'verbose_name': 'Menu Item', 'verbose_name_plural': 'Menu Items'},
        ),
        migrations.AlterModelOptions(
            name='onlinepaymentrequest',
            options={'verbose_name': 'Online Payment Request', 'verbose_name_plural': 'Online Payment Requests'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='orderreturn',
            options={'verbose_name': 'Order Return', 'verbose_name_plural': 'Order Returns'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productattributevalue',
            options={'verbose_name': 'Product Attribute Value', 'verbose_name_plural': 'Product Attribute Values'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'Product Category', 'verbose_name_plural': 'Product Categories'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['position'], 'verbose_name': 'Product Image', 'verbose_name_plural': 'Product Images'},
        ),
        migrations.AlterModelOptions(
            name='refund',
            options={'verbose_name': 'Refund', 'verbose_name_plural': 'Refunds'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
        migrations.AlterModelOptions(
            name='servercustomersupportchat',
            options={'verbose_name': 'Customer Support Chat', 'verbose_name_plural': 'Customer Support Chats'},
        ),
        migrations.AlterModelOptions(
            name='userpermission',
            options={'verbose_name': 'User Permission', 'verbose_name_plural': 'User Permissions'},
        ),
        migrations.AlterModelOptions(
            name='wishlist',
            options={'verbose_name': 'Wishlist', 'verbose_name_plural': 'Wishlists'},
        ),
        migrations.AlterModelOptions(
            name='wishlistitem',
            options={'verbose_name': 'Wishlist Item', 'verbose_name_plural': 'Wishlist Items'},
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='membership',
            name='tier',
            field=models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum'), ('diamond', 'Diamond')], max_length=50),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('tier',), name='unique_membership_tier'),
        ),
    ]
