# Generated by Django 6.0.1 on 2026-02-23 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backends', '0009_category_category_image_product_avl_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
