# Generated by Django 6.0.1 on 2026-02-23 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backends', '0010_remove_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='position',
            field=models.IntegerField(default=1),
        ),
    ]
