# Generated by Django 6.0.1 on 2026-02-23 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backends', '0012_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(default=1234, max_length=128),
            preserve_default=False,
        ),
    ]
